### ISSUE TITLE
WebIOPi is reporting to Google Analytics

### ISSUE THREAD

**Issue by MichaIng** [Freenove/WebIOPi#2]
Not sure if anyone recognised this: https://github.com/Freenove/WebIOPi/blob/master/WebIOPi-0.7.1/htdocs/webiopi.js#L139-L147

Can be seen in browser console as well. For the original version this might be fine, but for a fork, after 6 years no original authors activity, I think this should be removed.

Ah recognised in the other fork, here the related commit: https://github.com/thortex/rpi3-webiopi/commit/8923730f1d18d9b95464b733237342cdb8540890

**Comment by MichaIng** [comment]
Addressed with: #3

**Comment by SuhaylZhao** [comment]
Thanks！
